services:

  db:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d library"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: ./library_api
      dockerfile: Dockerfile
    container_name: library_api
    ports:
      - "5000:5000"
    volumes:
      - ./library_api:/app
    env_file:
      - ./library_api/.env
    depends_on:
      - db
    
  ui:
    build:
      context: ./library_ui
      dockerfile: Dockerfile
    container_name: library_ui
    ports:
      - "80:80"
    depends_on:
      - api


volumes:
  db_data: